[project]
name = "gte1-buildtools"
version = "1.0.0"
description = "Build tools for GTE1 Modpack"
requires-python = ">=3.14"
dependencies = [
    "json5>=0.12.1",
    "requests>=2.32.5",
]

[tool.uv]
package = false
